name: CI/CD

on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm --prefix frontend ci
      - name: Lint
        run: npm --prefix frontend run lint

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: MyPy
        run: mypy backend
      - name: Black
        run: black backend
      - name: Ruff
        run: ruff check backend

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: frontend-lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm --prefix frontend ci
      - name: Build
        run: npm --prefix frontend run build

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs:
      - backend-lint
      - frontend-build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker containers
        run: docker compose build

  deploy-production:
    name: Deploy Production
    runs-on: [self-hosted]
    needs:
      - docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Build and start containers
        run: |
          docker compose build
          docker compose up -d --remove-orphans
